# Generated by Django 5.0.2 on 2024-02-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_slug_alter_project_technology'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='slug',
        ),
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.CharField(default='empty', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='githublink',
            field=models.SlugField(max_length=40),
        ),
    ]
