# Generated by Django 5.0.2 on 2024-02-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_project_slug_project_short_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='githublink',
            field=models.SlugField(),
        ),
    ]
