# Generated by Django 5.0.2 on 2024-02-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_githublink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='githublink',
            field=models.CharField(max_length=60),
        ),
    ]
